# Production Environment Dockerfile

# Use the official Node.js image as a base image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /frontend/prod
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm ci
COPY . ./

# No need to EXPOSE a port here, as we will use docker-compose to manage the ports

# Start the server
CMD [ "npm", "run", "dev"]