# Devlopment Environment Dockerfile

# Use the official Node.js image as a base image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /frontend/dev
COPY package.json package-lock.json ./

# Install dependencies, including dev dependencies
RUN npm ci --include=dev
COPY . ./

# No need to EXPOSE a port here, as we will use docker-compose to manage the ports

# Start the development server with hot reloading
CMD [ "npm", "run", "dev" ]