# Use the official Node.js 18 alpine lightweight image as the base image
FROM node:18-alpine

# # Set the working directory inside the container to /app/frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . ./

# Expose port 5173 to allow external access
EXPOSE 5173

# Start the application using the command "npm run dev"
CMD [ "npm", "run", "dev"]