version: '2.4'  # Keeping your original version

services:  
  frontend:
    image: aryankharenagarro/frontend:latest
    container_name: frontend-production
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=http://backend:${BACKEND_PORT}  
    mem_limit: 512m
    cpus: 0.5
    networks:
      - app-network
    depends_on:
      - backend
    user: root

  backend:
    image: aryankharenagarro/backend:latest
    container_name: backend-production
    depends_on:
      - mongo
      - redis
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MONGO_URL=mongodb://mongo:27017/${MONGO_DB_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
    mem_limit: 1g
    cpus: 1.0
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-production
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: