version: '3.8'

services:  
  frontend:
    image: aryankharenagarro/frontend:${TAG:-latest}
    container_name: frontend-production
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=http://backend:${BACKEND_PORT}  
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started

  backend:
    image: aryankharenagarro/backend:${TAG:-latest}
    container_name: backend-production
    depends_on:
      - mongo
      - redis
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MONGO_URL=mongodb://mongo:27017/${MONGO_DB_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-production
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: