version: '2.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend:dev
    container_name: frontend_dev
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:${DEV_BACKEND_PORT}
      - FRONTEND_PORT=${DEV_FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${DEV_FRONTEND_PORT}:${DEV_FRONTEND_PORT}"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend:dev
    container_name: backend_dev
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${DEV_BACKEND_PORT}
      - MONGO_URL=mongodb://mongo:27017/${DEV_MONGO_DB_NAME}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${DEV_BACKEND_PORT}:${DEV_BACKEND_PORT}"
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - app-network
  
  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local