version: '2.4'  # Keeping your original version

services:  
  frontend:
    image: aryankharenagarro/frontend:latest
    container_name: frontend-production
    ports:
      - "${PROD_FRONTEND_PORT}:80"
    env_file:
      - .env
    environment:
      - FRONTEND_PORT=${PROD_FRONTEND_PORT}
      - BACKEND_URL=http://backend-production:${PROD_BACKEND_PORT}  
    mem_limit: 512m
    cpus: 0.5
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started
    user: root

  backend:
    image: aryankharenagarro/backend:latest
    container_name: backend-production
    ports:
      - "${PROD_BACKEND_PORT}:${PROD_BACKEND_PORT}"
    mem_limit: 1g
    cpus: 1.0
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/${PRODMONGO_DB_NAME}
      - BACKEND_PORT=${PROD_BACKEND_PORT}
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    

  mongo:
    image: mongo:latest
    container_name: mongo-production
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: