version: "3.3"

services:
  todo-backend:
    image: aryankharenagarro/todo-backend:latest
    container_name: todo-backend
    working_dir: /app/backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
  
  todo-frontend:
    image: aryankharenagarro/todo-frontend:latest
    container_name: todo-frontend
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    depends_on:
      - todo-backend
  
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"