version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend-dev
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - mongo
      - redis
    networks:
      todo-dev-network:
        driver: bridge
    volumes:
      - mongodb_data: data/db
	
  