# Testing Environment Dockerfile

# Use the official Node.js image as the base image
FROM node:18-slim

# Set the working directory in the container to /backend/test
WORKDIR /backend/test
COPY package.json package-lock.json ./

# Install the dependencies for the test environment
RUN npm ci --include=dev
COPY . ./

# No need to EXPOSE a port here, as we will use docker-compose to manage the ports

CMD [ "npm", "test" ]