# Production Environment Dockerfile

FROM node:18-slim
WORKDIR /backend/prod
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY . ./
# No need to EXPOSE a port here, as we will use docker-compose to manage the ports
CMD [ "node", "index.js" ]
# Note: The production Dockerfile is similar to the development one, but it installs only production dependencies and uses `node` instead of `nodemon` to run the application.