# Testing Environment Dockerfile

FROM node:slim
WORKDIR /backend/test
COPY package.json package-lock.json ./
RUN npm install
COPY . ./
# No need to EXPOSE a port here, as we will use docker-compose to manage the ports
CMD [ "npm", "test" ]