name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}      
      - name: Build and push production images
        run: |
          docker build -f backend/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          
          docker build -f frontend/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Deploy to local machine
        uses: appleboy/ssh-action@master
        with:
          envs: DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          script: |
            cd ../../scripts
            chmod +x deploy-prod.sh
            ./deploy-prod.sh